# Generated by Django 2.0.6 on 2018-06-06 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('consultation_id', models.AutoField(primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=500)),
                ('line_1', models.IntegerField()),
                ('chng_1', models.IntegerField()),
                ('line_2', models.IntegerField()),
                ('chng_2', models.IntegerField()),
                ('line_3', models.IntegerField()),
                ('chng_3', models.IntegerField()),
                ('line_4', models.IntegerField()),
                ('chng_4', models.IntegerField()),
                ('line_5', models.IntegerField()),
                ('chng_5', models.IntegerField()),
                ('line_6', models.IntegerField()),
                ('chng_6', models.IntegerField()),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('conclusion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'consultation',
            },
        ),
        migrations.CreateModel(
            name='Hexagram',
            fields=[
                ('hexagram_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=10000)),
            ],
            options={
                'managed': False,
                'db_table': 'hexagram',
            },
        ),
        migrations.CreateModel(
            name='HexagramLine',
            fields=[
                ('hexagram_line_id', models.IntegerField(primary_key=True, serialize=False)),
                ('translation', models.CharField(max_length=500)),
                ('commentary', models.CharField(max_length=1000)),
            ],
            options={
                'managed': False,
                'db_table': 'hexagram_line',
            },
        ),
        migrations.CreateModel(
            name='HLinePosition',
            fields=[
                ('h_line_position_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('meaning', models.CharField(max_length=500)),
            ],
            options={
                'managed': False,
                'db_table': 'h_line_position',
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('line_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'managed': False,
                'db_table': 'line',
            },
        ),
        migrations.CreateModel(
            name='LineChanges',
            fields=[
                ('line_changes_id', models.IntegerField(primary_key=True, serialize=False)),
                ('line_1', models.IntegerField()),
                ('line_2', models.IntegerField()),
                ('line_3', models.IntegerField()),
                ('line_4', models.IntegerField()),
                ('line_5', models.IntegerField()),
                ('line_6', models.IntegerField()),
                ('chng_1', models.IntegerField()),
                ('chng_2', models.IntegerField()),
                ('chng_3', models.IntegerField()),
                ('chng_4', models.IntegerField()),
                ('chng_5', models.IntegerField()),
                ('chng_6', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'line_changes',
            },
        ),
        migrations.CreateModel(
            name='Trigram',
            fields=[
                ('trigram_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'managed': False,
                'db_table': 'trigram',
            },
        ),
        migrations.CreateModel(
            name='TrigramLine',
            fields=[
                ('trigram_line_id', models.IntegerField(primary_key=True, serialize=False)),
                ('t_line_position', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'trigram_line',
            },
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('hexagram1_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='h1', serialize=False, to='ichingdb.Hexagram')),
            ],
            options={
                'managed': False,
                'db_table': 'pair',
            },
        ),
    ]
